name = "Open62541"
uuid = "e9b70463-8ccb-4e30-a2e2-0d1ec8db6536"
authors = ["Martin Kosch <martin.kosch@gmail.com> and contributors"]
version = "0.4.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
open62541_jll = "de311183-6042-582f-9ed9-05a52085bec4"

[compat]
Aqua = "0.8"
Base64 = "1.6"
CEnum = "0.4, 0.5"
Dates = "1.6"
Distributed = "1.6"
DocStringExtensions = "0.9"
OffsetArrays = "1"
Pkg = "1.6"
Random = "1.6"
SafeTestsets = "0.1.0"
Test = "1.6"
julia = "1.6"
open62541_jll = "~1.4.1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Base64", "Distributed", "Pkg", "Random", "SafeTestsets", "Test"]
