[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
Clang = "40e3b903-d033-50b4-a0cc-940c62c95e31"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
open62541_jll = "de311183-6042-582f-9ed9-05a52085bec4"

[compat]
Clang = "0.18"
JuliaFormatter = "1.0.42"
OffsetArrays = "1.12.10"
open62541_jll = "~1.4.1"
